In [2]:
#imports
import pandas as pd
import scipy.stats as stats
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.metrics import accuracy_score

In [21]:
#load all dfs
#dummy_2018 = pd.read_csv('dummy_2018.csv')
#dummy_2019 = pd.read_csv('dummy_2019.csv')
#dummy_2020 = pd.read_csv('dummy_2020.csv')
#dummy_2021 = pd.read_csv('dummy_2021.csv')
dummy_2022 = pd.read_csv('dummy_2022.csv')
dummy_2022

,activity_year,action_taken,loan_amount,loan_to_value_ratio,loan_term,property_value,total_units,income,applicant_race_observed,co-applicant_race_observed,...,applicant_age_above_62_Yes,submission_of_application_Submitted directly to your institution,initially_payable_to_institution_Not applicable,initially_payable_to_institution_Not initially payable to your institution,aus-1_Guaranteed Underwriting System (GUS),aus-1_Internal Proprietary System,aus-1_Loan Prospector (LP) or Loan Product Advisor,aus-1_Not applicable,aus-1_Other,aus-1_Technology Open to Approved Lenders (TOTAL) Scorecard
0,2022,1,135000.0,90.000,360.0,155000.0,1,33.0,2,4,...,0,1,0,0,0,0,0,1,0,0
1,2022,0,185000.0,90.000,360.0,205000.0,3,52.0,2,4,...,0,1,0,0,0,0,0,1,0,0
2,2022,1,255000.0,86.897,360.0,295000.0,1,72.0,1,4,...,0,1,0,0,0,0,0,1,0,0
3,2022,1,165000.0,72.727,360.0,225000.0,1,38.0,1,4,...,0,1,0,0,0,0,0,1,0,0
4,2022,1,265000.0,85.000,360.0,315000.0,1,69.0,2,2,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83403,2022,1,295000.0,80.000,360.0,365000.0,1,150.0,2,2,...,0,1,0,0,0,0,0,0,0,0
83404,2022,1,205000.0,95.000,360.0,225000.0,1,86.0,2,4,...,0,1,0,0,0,0,0,0,0,0
83405,2022,1,205000.0,90.000,360.0,235000.0,1,129.0,2,4,...,0,1,0,0,0,0,1,0,0,0
83406,2022,1,525000.0,85.000,360.0,615000.0,1,120.0,2,4,...,0,1,0,0,0,0,1,0,0,0
83407,2022,1,285000.0,96.500,360.0,295000.0,1,80.0,2,4,...,0,1,0,0,0,0,0,0,0,1

In [15]:
corr_matrix_2022 = dummy_2022.corr()
corr_matrix_2022 = corr_matrix_2022.dropna(axis='columns', how='all')
corr_matrix_2022 = corr_matrix_2022.dropna(axis='index', how='all')
corr_matrix_2022

,action_taken,loan_amount,loan_to_value_ratio,property_value,total_units,income,applicant_race_observed,co-applicant_race_observed,tract_population,tract_minority_population_percent,...,applicant_age_above_62_Yes,submission_of_application_Submitted directly to your institution,initially_payable_to_institution_Not applicable,initially_payable_to_institution_Not initially payable to your institution,aus-1_Guaranteed Underwriting System (GUS),aus-1_Internal Proprietary System,aus-1_Loan Prospector (LP) or Loan Product Advisor,aus-1_Not applicable,aus-1_Other,aus-1_Technology Open to Approved Lenders (TOTAL) Scorecard
action_taken,1.000000,0.031069,-0.101234,0.047256,-0.125615,0.133374,0.029952,-0.054256,0.024200,-0.162128,...,-0.009303,0.041573,-0.361300,0.020079,-0.001753,-0.121790,0.093524,-0.164058,-0.045431,-0.098005
loan_amount,0.031069,1.000000,-0.071456,0.953420,0.091817,0.634256,-0.043289,-0.235324,0.135373,-0.041063,...,-0.090279,-0.087824,-0.007633,0.054265,-0.084117,-0.004233,0.054280,-0.037165,-0.013146,-0.077748
loan_to_value_ratio,-0.101234,-0.071456,1.000000,-0.312620,0.035608,-0.171661,0.029072,0.081961,-0.071850,0.176325,...,-0.139478,-0.004291,0.041770,-0.035399,0.067275,-0.010367,-0.134136,-0.029861,-0.010612,0.234136
property_value,0.047256,0.953420,-0.312620,1.000000,0.074891,0.648703,-0.047805,-0.242674,0.141455,-0.085876,...,-0.053439,-0.075461,-0.019182,0.059540,-0.089513,0.015458,0.080865,-0.008282,0.005738,-0.136067
total_units,-0.125615,0.091817,0.035608,0.074891,1.000000,-0.009618,-0.008561,0.051178,-0.066276,0.236920,...,-0.015824,-0.033527,0.038149,-0.003733,-0.013108,0.000874,-0.036204,0.016994,0.036903,0.096102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
aus-1_Internal Proprietary System,-0.121790,-0.004233,-0.010367,0.015458,0.000874,-0.002031,-0.024303,0.004368,-0.002306,0.013955,...,0.020964,0.019719,-0.010511,-0.020019,-0.006486,1.000000,-0.046521,-0.016487,-0.004967,-0.030124
aus-1_Loan Prospector (LP) or Loan Product Advisor,0.093524,0.054280,-0.134136,0.080865,-0.036204,0.055844,-0.046506,-0.007504,0.030678,-0.068621,...,-0.003914,-0.060100,-0.033718,0.078626,-0.046217,-0.046521,1.000000,-0.117485,-0.035394,-0.214662
aus-1_Not applicable,-0.164058,-0.037165,-0.029861,-0.008282,0.016994,-0.019261,-0.032297,0.000671,-0.011925,0.030036,...,0.009800,0.029757,0.016037,-0.002314,-0.016379,-0.016487,-0.117485,1.000000,-0.012543,-0.076076
aus-1_Other,-0.045431,-0.013146,-0.010612,0.005738,0.036903,-0.004595,-0.013660,-0.007559,-0.009666,0.035395,...,0.020382,0.020653,-0.007997,-0.012715,-0.004934,-0.004967,-0.035394,-0.012543,1.000000,-0.022919
aus-1_Technology Open to Approved Lenders (TOTAL) Scorecard,-0.098005,-0.077748,0.234136,-0.136067,0.096102,-0.132841,-0.045228,0.040660,-0.065088,0.169936,...,-0.035057,0.011343,0.064884,-0.062875,-0.029928,-0.030124,-0.214662,-0.076076,-0.022919,1.000000

In [17]:
def filter_by_index_start(df, lst):
    mask = df.index.to_series().apply(lambda x: any(x.startswith(string) for string in lst))
    filtered_df = df[mask]
    return filtered_df

In [22]:
def filter_by_index_columns(df, lst):
    # Filter rows based on index starting with any prefix in lst
    mask = df.index.to_series().apply(lambda x: any(x.startswith(prefix) for prefix in lst))
    filtered_df = df[mask]
    
    # Remove columns that start with any prefix found in lst
    filtered_df = filtered_df.loc[:, ~filtered_df.columns.to_series().apply(lambda col: any(col.startswith(prefix) for prefix in lst))]
    
    return filtered_df

In [25]:
lst = ['derived_ethnicity', 'derived_race', 'derived_sex', 'applicant_ethnicity', 'co-applicant_ethnicity']
filtered_matrix = filter_by_index_columns(corr_matrix_2022, lst)
filtered_matrix

,action_taken,loan_amount,loan_to_value_ratio,property_value,total_units,income,applicant_race_observed,co-applicant_race_observed,tract_population,tract_minority_population_percent,...,applicant_age_above_62_Yes,submission_of_application_Submitted directly to your institution,initially_payable_to_institution_Not applicable,initially_payable_to_institution_Not initially payable to your institution,aus-1_Guaranteed Underwriting System (GUS),aus-1_Internal Proprietary System,aus-1_Loan Prospector (LP) or Loan Product Advisor,aus-1_Not applicable,aus-1_Other,aus-1_Technology Open to Approved Lenders (TOTAL) Scorecard
derived_ethnicity_Free Form Text Only,-0.008226,-0.002652,0.001749,-0.002355,-0.001959,-0.005953,-0.001952,0.002034,-0.000781,0.007035,...,0.004320,0.005274,-0.001560,-0.002972,-0.000963,0.023936,-0.006907,0.002655,-0.000737,0.001635
derived_ethnicity_Hispanic or Latino,-0.059845,-0.036728,0.127996,-0.070114,0.073284,-0.157600,-0.018084,0.038151,0.019263,0.265047,...,-0.062742,-0.021523,0.015109,-0.032489,-0.029551,-0.001010,-0.057487,0.041824,0.016409,0.052852
derived_ethnicity_Joint,0.014685,0.054990,0.007681,0.048994,-0.006268,0.083217,0.004461,-0.188828,0.004379,-0.010681,...,-0.020986,0.012505,-0.006403,-0.000792,-0.007722,-0.001022,0.002363,-0.010939,0.005647,-0.005143
derived_ethnicity_Not Hispanic or Latino,0.078295,0.011839,-0.115404,0.043076,-0.069128,0.097080,-0.000667,0.023171,-0.013936,-0.231254,...,0.047929,-0.015733,-0.029091,0.053404,0.028754,0.005976,0.058233,-0.028024,-0.010128,-0.063969
derived_race_American Indian or Alaska Native,-0.011640,-0.023969,0.015945,-0.026021,0.005081,-0.032022,-0.001526,0.027162,0.001246,0.020269,...,-0.006053,0.012503,0.003233,-0.011193,-0.003377,0.005242,-0.005669,0.008074,-0.001416,0.009795
derived_race_Asian,-0.005290,0.135914,-0.091075,0.153409,-0.017712,0.075530,-0.027175,0.030154,0.058858,0.016723,...,-0.033287,-0.115462,-0.002756,0.022269,-0.020775,0.007412,0.039367,-0.011429,-0.004610,-0.063119
derived_race_Black or African American,-0.136992,-0.074388,0.194634,-0.117949,0.089149,-0.105389,-0.014106,0.129484,-0.085840,0.369937,...,0.053445,0.014613,0.052676,-0.039604,-0.026315,0.015843,-0.095996,0.014510,0.025661,0.198964
derived_race_Free Form Text Only,0.002159,-0.001517,0.004862,-0.002474,-0.000979,-0.002036,-0.000976,-0.000051,0.003060,0.000460,...,-0.001683,0.002637,-0.000780,-0.001486,-0.000481,0.024419,-0.003453,-0.001224,-0.000369,-0.002236
derived_race_Joint,0.011692,0.057788,-0.001824,0.054956,-0.013700,0.089994,0.003002,-0.184803,0.008716,-0.018508,...,-0.012757,0.020877,-0.005335,-0.007074,-0.000484,-0.000621,-0.004734,-0.001784,-0.005266,-0.009915
derived_race_Native Hawaiian or Other Pacific Islander,-0.016058,-0.005939,0.008492,-0.007342,0.008440,-0.007471,-0.003515,0.011052,-0.001413,0.008935,...,-0.001045,0.000678,-0.000914,0.002502,-0.002456,-0.002472,-0.009451,0.009776,0.004524,0.006568
derived_race_Race Not Available,-0.047994,0.007960,0.031720,0.000353,0.025118,-0.002321,0.018502,0.013893,-0.006037,0.068870,...,-0.001969,0.067666,0.026167,-0.046837,-0.008668,-0.003151,-0.019567,0.004241,-0.009133,0.037641
derived_race_White,0.131802,-0.036286,-0.113354,-0.008533,-0.068112,0.016561,0.010273,-0.069068,0.030925,-0.312196,...,-0.013429,-0.006422,-0.052140,0.052431,0.036041,-0.013508,0.062936,-0.008113,-0.007607,-0.131808
derived_sex_Joint,0.073519,0.231690,-0.088665,0.242511,-0.056341,0.367935,0.003410,-0.865571,0.053589,-0.148765,...,0.037906,0.027902,-0.029757,-0.004251,-0.012484,-0.003760,0.013760,-0.001049,0.007222,-0.063762
derived_sex_Male,-0.021736,-0.047592,0.038945,-0.054767,0.040905,-0.126323,-0.020563,0.456150,-0.006802,0.019263,...,-0.067380,-0.054552,0.004593,0.029232,0.011120,0.010245,0.001101,0.017124,0.001791,-0.024424
derived_sex_Sex Not Available,-0.033789,-0.008500,-0.000383,-0.006514,0.008662,0.012083,0.021325,0.015368,-0.010843,0.005292,...,0.003983,0.037994,0.025415,-0.026672,-0.004870,-0.008775,-0.010538,0.000139,-0.008999,0.030425
applicant_ethnicity-1_Hispanic or Latino,-0.050084,-0.023454,0.126758,-0.057677,0.069341,-0.135354,-0.014893,0.001878,0.020690,0.251111,...,-0.066284,-0.022111,0.014857,-0.030051,-0.031142,-0.005356,-0.053838,0.035181,0.012266,0.049352
"applicant_ethnicity-1_Information not provided by applicant in mail, internet, or telephone application",-0.051376,0.000310,0.010022,-0.002014,0.016137,0.008960,0.021602,0.013356,-0.005532,0.022729,...,0.017087,0.044975,0.028868,-0.040149,-0.002466,-0.008341,-0.017102,-0.004707,-0.008260,0.033581
applicant_ethnicity-1_Mexican,-0.011410,-0.005468,0.015004,-0.008630,0.006352,-0.022066,-0.008360,0.010220,-0.000083,0.041375,...,-0.011220,0.005082,-0.000128,-0.005505,-0.006152,0.005570,-0.008096,0.012478,0.008137,0.006042
applicant_ethnicity-1_Not Hispanic or Latino,0.081258,0.021605,-0.116632,0.052543,-0.071144,0.113668,0.000705,-0.012903,-0.013343,-0.235836,...,0.045185,-0.012557,-0.030880,0.053637,0.028002,0.006527,0.059211,-0.029921,-0.009151,-0.066228
applicant_ethnicity-1_Not applicable,0.001763,-0.000459,0.004236,-0.001623,-0.000800,0.001895,0.017486,0.000830,0.008531,-0.004287,...,-0.001374,0.002153,-0.000637,-0.001213,-0.000393,-0.000396,-0.002819,-0.000999,-0.000301,-0.001826
applicant_ethnicity-1_Other Hispanic or Latino,-0.022036,-0.010629,0.000712,-0.010339,0.009105,-0.011671,-0.005550,0.008513,-0.003814,0.010137,...,0.010237,-0.001287,-0.003619,-0.004004,0.003950,0.014885,-0.008818,0.012603,0.014707,0.008766
applicant_ethnicity-1_Puerto Rican,-0.004053,0.000511,0.009831,-0.001006,0.000823,-0.005865,-0.005379,-0.002348,0.000034,0.014099,...,-0.002293,0.006646,-0.004299,-0.003521,0.006454,0.001854,-0.000551,-0.004890,0.015759,0.006540
co-applicant_ethnicity-1_Hispanic or Latino,-0.014647,0.057167,0.069561,0.032147,0.007226,0.034744,-0.007949,-0.345911,0.028912,0.108606,...,-0.024553,-0.009867,0.000264,-0.020285,-0.014747,-0.006597,-0.037996,0.014418,0.006559,0.035572
"co-applicant_ethnicity-1_Information not provided by applicant in mail, internet, or telephone application",-0.009570,0.056872,-0.014440,0.056335,-0.012206,0.111825,0.015145,-0.266062,0.014266,-0.024039,...,0.025167,0.029728,0.013500,-0.020485,-0.007669,-0.005440,-0.009269,-0.006288,-0.005748,0.010241
co-applicant_ethnicity-1_Mexican,-0.003727,0.009215,-0.003496,0.008652,0.002460,0.010439,-0.001707,-0.064580,0.004019,0.020562,...,-0.004986,0.001296,0.002108,-0.004780,-0.003712,-0.000500,-0.002593,0.013110,0.005642,0.004189
co-applicant_ethnicity-1_No co-applicant,-0.056792,-0.234660,0.080413,-0.241584,0.052953,-0.392632,-0.005104,0.986326,-0.056832,0.124514,...,-0.040272,-0.023933,0.017455,0.010071,0.017192,0.006454,-0.003490,0.003399,-0.006260,0.045746
co-applicant_ethnicity-1_Not Hispanic or Latino,0.076272,0.201906,-0.120538,0.223632,-0.057292,0.364962,0.004032,-0.774860,0.040514,-0.189639,...,0.046551,0.018472,-0.025403,0.008987,-0.006897,-0.001134,0.029605,-0.010829,0.003668,-0.075816
co-applicant_ethnicity-1_Not applicable,0.004829,0.001647,-0.004875,0.003090,-0.002190,-0.018480,0.001155,-0.004888,0.011357,0.000342,...,-0.000326,-0.006236,-0.001745,0.019659,-0.001077,-0.001084,-0.001519,0.020085,-0.000824,-0.005000
co-applicant_ethnicity-1_Other Hispanic or Latino,-0.011417,0.007003,0.000317,0.006483,-0.001246,0.012494,-0.004751,-0.041372,-0.008237,0.003103,...,0.010775,-0.000555,-0.000583,0.001574,-0.002343,-0.002358,-0.005397,0.000340,0.018344,0.010468
co-applicant_ethnicity-1_Puerto Rican,0.001014,0.006368,0.004123,0.004943,-0.003577,0.011267,-0.003565,-0.031377,0.002363,0.003853,...,0.002274,0.006659,-0.002849,-0.003081,-0.001758,-0.001770,-0.001214,-0.001674,0.007595,0.003544
applicant_ethnicity_observed_Not applicable,0.027179,-0.059567,0.030996,-0.063612,-0.010568,-0.035471,0.885086,0.081903,-0.001356,-0.062623,...,-0.007989,0.096223,0.006046,-0.026458,0.041186,-0.020221,-0.043669,-0.026378,-0.015384,-0.054424
applicant_ethnicity_observed_Not collected on the basis of visual observation or surname,-0.019346,0.062838,-0.024935,0.065250,0.010362,0.046807,-0.579818,-0.059860,0.003753,0.055927,...,-0.000823,-0.044472,-0.005577,-0.004510,-0.040584,0.011384,0.030186,0.016168,0.012860,0.052152
co-applicant_ethnicity_observed_No co-applicant,-0.056792,-0.234660,0.080413,-0.241584,0.052953,-0.392632,-0.005104,0.986326,-0.056832,0.124514,...,-0.040272,-0.023933,0.017455,0.010071,0.017192,0.006454,-0.003490,0.003399,-0.006260,0.045746
co-applicant_ethnicity_observed_Not applicable,0.020102,0.012784,-0.000754,0.011521,-0.016132,0.058661,0.493328,-0.053030,0.011939,-0.049230,...,-0.000276,0.055230,0.000662,-0.013639,0.016277,-0.011595,-0.023074,-0.011871,-0.008822,-0.039436
co-applicant_ethnicity_observed_Not collected on the basis of visual observation or surname,0.051875,0.234895,-0.079848,0.241935,-0.048881,0.380684,-0.111207,-0.966175,0.054102,-0.110568,...,0.038961,0.014268,-0.017772,-0.009642,-0.022678,-0.003905,0.009473,-0.001615,0.009224,-0.033900